# Generated by Django 5.1.2 on 2024-11-14 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="shares",
            field=models.ManyToManyField(
                blank=True, related_name="shares_articles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="ArticleShare",
        ),
    ]
