# Generated by Django 5.1.2 on 2024-11-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="type",
            field=models.CharField(default="type", max_length=50),
        ),
        migrations.AlterField(
            model_name="articleshare",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Facebook", "Facebook"),
                    ("Twitter", "Twitter"),
                    ("Instagram", "Instagram"),
                    ("Threads", "Threads"),
                ],
                max_length=50,
            ),
        ),
    ]
